<?php

namespace Hessam\MailQueueBundle\Repository;

use Hessam\MailQueueBundle\Entity\MailQueue;
use Doctrine\ORM\EntityRepository;

/**
 * MailQueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailQueueRepository extends EntityRepository
{
  /**
   * @param \DateTime $time
   * @param string $environment
   * @return MailQueue[]
   */
  public function findEmailsForDelete(\DateTime $time, $environment){
    return $this->createQueryBuilder("emails")
      ->where("emails.status =  :status")
      ->andWhere("emails.environment = :environment")
      ->andWhere("emails.sendAt < :sentAtTime")
      ->setParameter("status",MailQueue::STATUS_COMPLETE)
      ->setParameter("environment",$environment)
      ->setParameter("sentAtTime",$time)
      ->getQuery()
      ->execute();
  }
}
